# Generated by Django 6.0 on 2025-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvestment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
