# Generated by Django 6.0 on 2025-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_customerinvestment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvestment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
