# Generated by Django 6.0 on 2025-12-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_customerinvestment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='non_of_days',
            field=models.IntegerField(default=30),
        ),
    ]
