# Generated by Django 6.0 on 2025-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_investment_non_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='profit_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
