# Generated by Django 6.0 on 2025-12-14 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_investment_profit_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeWealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wallet_address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
